name: facility
description: Flutter application for Facility platform
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  otp_text_field: ^1.1.3
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: assets/images/logo.png
    background_color: "#ffffff"
    theme_color: "#ffffff"
  image_path: assets/images/logo.png
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/images/logo.png
